---
- name: Setup sg bastion hosts
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import bastion setup variable
      include_vars: vars/vpc_setup
    - name: Import VPC setup variable
      include_vars: vars/vpc_output_vars
    - name: Create bastion host ec2 key
      ec2_key:
        name: sg-key
        region: "{{region}}"
      register: key_out
    - name: Save private key into file bastion-key.pem
      copy:
        content: "{{key_out.key.private_key}}"
        dest: "./bastion-key.pem"
        mode: 0600
      when: key_out.changed
    - name: Create Security Group for bastion host
      ec2_group:
        name: Bastion-host-sg
        description: Allow port 22 from everywhere and all port within sg
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "{{MYIP}}"
      register: BastionSG_out
    - name: Create Bastion host
      ec2_instance:
        key_name: sg-key
        region: "{{region}}"
        instance_type: t2.micro
        image: "{{bastion_ami}}"
        wait: yes
        wait_timeout: 300
        instance_tags:
          Name: "Bastion_host"
          Project: sg
          Owner: DevOps Team
        exact_count: 1
        count_tag:
          Name: "Bastion_host"
          Project: sg
          Owner: DevOps Team
        group_id : "{{BastionSG_out.group_id}}"
        vpc_subnet_id: "{{pubsub1id}}"
      register: bastionHost_out
    - name: Insert/Update "BastionSGid" in vars/vpc_output_vars
      blockinfile:
        path: vars/vpc_output_vars
        backup: yes
        block: |
          BastionSGid: "{{BastionSG_out.group_id}}"


