- name: Build artifact ROOT.war & SQL file to be copied in files/ directory
  import_playbook: build.yaml

- name: Set Hosts to IP Mapping in /etc/hosts file of all servers
  import_playbook: set_host_ip_map.yaml

- name: Setup dbserver
  import_playbook: db.yaml

- name: Deploy SQL file on dbserver
  import_playbook: dbdeploy.yaml

- name: Setup memcache service
  import_playbook: memcache.yaml

- name: Setup rabbitmq service
  import_playbook: rabbitmq.yaml

- name: Setup tomcat application server
  import_playbook: appserver.yaml

- name: Setup Nginx webserver
  import_playbook: web.yaml